USE Digital_Library_Management_System_with_Role_Based_Security_and_Reservations

CREATE LOGIN Librarians WITH PASSWORD = '123123';
CREATE USER Li FOR LOGIN Librarians;
GRANT SELECT, UPDATE, INSERT ON Article TO Li;
GRANT SELECT, UPDATE, INSERT ON Books TO Li;
GRANT SELECT, UPDATE, INSERT ON ElectronicResources TO Li;
GRANT SELECT, UPDATE, INSERT ON Journal TO Li;
GRANT SELECT, UPDATE, INSERT ON Magazine TO Li;
GRANT SELECT, UPDATE, INSERT ON Author TO Li;
GRANT SELECT, UPDATE, INSERT ON Members TO Li;
GRANT SELECT, UPDATE, INSERT ON Reservations TO Li;
GRANT SELECT, UPDATE, INSERT ON Resources TO Li;
GRANT SELECT, UPDATE, INSERT ON Transactions TO Li;
GRANT SELECT, UPDATE, INSERT ON Loans TO Li;
GRANT SELECT, UPDATE, INSERT ON Members TO Li;

CREATE LOGIN Members WITH PASSWORD = '123123';
CREATE USER Membr FOR LOGIN Members;
GRANT SELECT ON Article TO Membr;
GRANT SELECT ON Books TO Membr;
GRANT SELECT ON ElectronicResources TO Membr;
GRANT SELECT ON Journal TO Membr;
GRANT SELECT ON Magazine TO Membr;
GRANT SELECT ON Resources TO Membr;
GRANT SELECT, INSERT ON Loans TO Membr;
GRANT SELECT, INSERT ON Reservations TO Membr;
REVOKE SELECT, UPDATE, INSERT ON Author to Membr;
REVOKE SELECT, UPDATE, INSERT ON Librarian to Membr;
REVOKE SELECT, UPDATE, INSERT ON Transactions to Membr;
REVOKE SELECT, UPDATE, INSERT ON Members to Membr;


